package main

import (
	bptmux "blueprint/internal/tmux"
	"context"
	"encoding/json"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"time"

	"blueprint/internal/book"
	"blueprint/internal/cache"
	bpconfig "blueprint/internal/config"
	"blueprint/internal/release"
)

type doctorCheck struct {
	Agent    string   `json:"agent,omitempty"`
	ThreadID string   `json:"thread_id,omitempty"`
	Related  []string `json:"related_agents,omitempty"`
	Next     string   `json:"next_step,omitempty"`
	Name     string   `json:"name"`
	OK       bool     `json:"ok"`
	Warning  bool     `json:"warning,omitempty"`
	Detail   string   `json:"detail"`
}

func canonicalExecutable(path string) (string, error) {
	absolute, err := filepath.Abs(path)
	if err != nil {
		return "", err
	}
	resolved, err := filepath.EvalSymlinks(absolute)
	if err != nil {
		return "", err
	}
	return filepath.Clean(resolved), nil
}

func checkExecutablePath(found, running, launcher string) (string, error) {
	foundPath, err := canonicalExecutable(found)
	if err != nil {
		return "", fmt.Errorf("resolve bp on PATH (%s): %w", found, err)
	}
	runningPath, err := canonicalExecutable(running)
	if err != nil {
		return "", fmt.Errorf("resolve running bp (%s): %w", running, err)
	}
	if foundPath == runningPath {
		return found + " (running " + running + ")", nil
	}
	// npm starts the native binary through bp.js. Its launcher overwrites this
	// environment value with its own real path before spawning the child.
	if launcher != "" {
		launcherPath, launcherErr := canonicalExecutable(launcher)
		if launcherErr == nil && foundPath == launcherPath &&
			filepath.Base(launcherPath) == "bp.js" &&
			filepath.Dir(launcherPath) == filepath.Dir(runningPath) &&
			filepath.Base(runningPath) == release.Platform() {
			return found + " (launcher for " + running + ")", nil
		}
	}
	return "", fmt.Errorf("bp on PATH resolves to %s, but the running executable is %s", foundPath, runningPath)
}

func checkShellIntegration(path string) (string, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		if os.IsNotExist(err) {
			return "", fmt.Errorf("bp shell integration is missing at %s; run bp setup", path)
		}
		return "", fmt.Errorf("read bp shell integration %s: %w", path, err)
	}
	content := string(data)
	if content == localShell {
		return "active: " + path, nil
	}
	if content == "# Generated by bp setup. Disabled; native aliases and records are preserved.\n" {
		return "disabled: " + path, nil
	}
	if strings.HasPrefix(content, "# Generated by bp setup.") {
		return "", fmt.Errorf("incomplete bp shell integration: %s; run bp setup to repair it", path)
	}
	return "", fmt.Errorf("unrecognized shell integration: %s; inspect it before running bp setup", path)
}

func doctor(cfg bpconfig.Config, configErr error, args []string) error {
	jsonOutput, agentName := false, ""
	for i := 0; i < len(args); i++ {
		switch args[i] {
		case "--json":
			jsonOutput = true
		case "--agent":
			if i+1 >= len(args) {
				return fmt.Errorf("usage: bp doctor [--agent <name>] [--json]")
			}
			i++
			agentName = args[i]
		default:
			return fmt.Errorf("usage: bp doctor [--agent <name>] [--json]")
		}
	}
	if configErr == nil && cfg.InvalidConfig != "" {
		configErr = fmt.Errorf("%s", cfg.InvalidConfig)
	}
	checks := []doctorCheck{}
	add := func(name string, err error, detail string) {
		if err != nil {
			detail = err.Error()
		}
		checks = append(checks, doctorCheck{Name: name, OK: err == nil, Detail: detail})
	}
	add("config", configErr, cfg.Path)
	tmux, err := exec.LookPath("tmux")
	add("tmux", err, tmux)
	self, selfErr := os.Executable()
	found, err := exec.LookPath("bp")
	pathDetail := ""
	if err == nil && selfErr != nil {
		err = selfErr
	}
	if err == nil {
		pathDetail, err = checkExecutablePath(found, self, os.Getenv("BP_LAUNCHER_PATH"))
	}
	add("PATH", err, pathDetail)
	shell := filepath.Base(os.Getenv("SHELL"))
	err = nil
	if shell != "bash" && shell != "zsh" {
		err = fmt.Errorf("unsupported shell %s", shell)
	}
	add("shell", err, shell)
	if configErr == nil {
		fleet, err := book.LoadFleet(book.Paths(cfg.Agentbooks))
		add("agentbook", err, fmt.Sprintf("%d agents, coordinator %s; bp book --json shows source paths", len(fleet.Agents), fleet.Root))
		if err == nil {
			checks = append(checks, doctorRuntimeChecks(cfg, fleet, agentName)...)
		}
	}
	home, _ := os.UserHomeDir()
	path := filepath.Join(home, ".config", "bp", "shell.sh")
	shellDetail, err := checkShellIntegration(path)
	add("shell_integration", err, shellDetail)
	clis := []string{}
	for _, name := range []string{"codex", "claude", "opencode", "hermes"} {
		if p, err := exec.LookPath(name); err == nil {
			clis = append(clis, p)
		}
	}
	err = nil
	if len(clis) == 0 {
		err = fmt.Errorf("no supported agent CLI on PATH")
	}
	add("agent_cli", err, fmt.Sprint(clis))
	ok := true
	for _, c := range checks {
		if !c.OK {
			ok = false
		}
	}
	if jsonOutput {
		json.NewEncoder(os.Stdout).Encode(struct {
			Version string        `json:"version"`
			OK      bool          `json:"ok"`
			Checks  []doctorCheck `json:"checks"`
		}{release.Version(), ok, checks})
	} else {
		for _, c := range checks {
			mark := "OK"
			if c.Warning {
				mark = "WARN"
			} else if !c.OK {
				mark = "FAIL"
			}
			fmt.Printf("%s %-18s %s\n", mark, c.Name, c.Detail)
			if c.Next != "" {
				fmt.Printf("  next: %s\n", c.Next)
			}
		}
	}
	if !ok {
		return errReported
	}
	return nil
}

func retainedLocalExitEvidence(cfg bpconfig.Config) map[string]map[string]localExitReport {
	evidence := map[string]map[string]localExitReport{}
	if cfg.StateDir == "" {
		return evidence
	}
	paths, _ := filepath.Glob(filepath.Join(cfg.StateDir, "local", "*", "exit.json"))
	for _, path := range paths {
		exit, ok := readLocalExitReport(path)
		if !ok || exit.Agent == "" || !localExitFailed(exit) {
			continue
		}
		if evidence[exit.Agent] == nil {
			evidence[exit.Agent] = map[string]localExitReport{}
		}
		evidence[exit.Agent][path] = exit
	}
	return evidence
}

func readLocalExitReport(path string) (localExitReport, bool) {
	data, err := os.ReadFile(path)
	if err != nil {
		return localExitReport{}, false
	}
	var exit localExitReport
	if json.Unmarshal(data, &exit) != nil {
		return localExitReport{}, false
	}
	if exit.ExitedAt == nil || exit.ExitedAt.IsZero() {
		if info, err := os.Stat(path); err == nil {
			stamp := info.ModTime().UTC()
			exit.ExitedAt = &stamp
		}
	}
	return exit, true
}

const localExitHistoricalAge = 24 * time.Hour

func localExitHistorical(exit localExitReport, registered, laterSuccess bool, now time.Time) bool {
	if !registered || laterSuccess {
		return true
	}
	return exit.ExitedAt != nil && !exit.ExitedAt.IsZero() && now.Sub(*exit.ExitedAt) > localExitHistoricalAge
}

func localExitDoctorCheck(name, path string, exit localExitReport, historical bool) doctorCheck {
	detail := exit.Harness + " exited with status " + exit.Status
	if exit.ExitedAt != nil && !exit.ExitedAt.IsZero() {
		detail += " at " + exit.ExitedAt.UTC().Format(time.RFC3339)
	}
	next := "The exit.json file is kept as evidence at " + path + "; read it with: cat " + quoteShell(path) + ". Resolve the cause before retrying; do not remove writer locks."
	check := doctorCheck{Name: "native_exit/" + name, Agent: name, Detail: detail, Next: next}
	if historical {
		check.OK = true
		check.Warning = true
		check.Detail = "historical exit: " + detail
		check.Next = "The exit.json file is kept as historical evidence at " + path + "; read it with: cat " + quoteShell(path) + "."
	}
	return check
}

func localExitDoctorChecks(name string, evidence map[string]localExitReport, historical bool) []doctorCheck {
	var checks []doctorCheck
	for path, exit := range evidence {
		checks = append(checks, localExitDoctorCheck(name, path, exit, historical))
	}
	return checks
}

func laterLaunchSucceeded(failurePath string, failure localExitReport, agent book.Agent, running bool) bool {
	if failure.ExitedAt == nil || failure.ExitedAt.IsZero() || agent.StatusAt.IsZero() || !agent.StatusAt.After(*failure.ExitedAt) {
		return false
	}
	if agent.Local != nil && agent.Local.Path != "" {
		currentPath := filepath.Clean(filepath.Join(filepath.Dir(agent.Local.Path), "exit.json"))
		if currentPath == filepath.Clean(failurePath) {
			return false
		}
		if current, ok := readLocalExitReport(currentPath); ok {
			return !localExitFailed(current) && current.ExitedAt != nil && current.ExitedAt.After(*failure.ExitedAt)
		}
	}
	return agent.Status == "open" && running
}

func doctorAgentIsRunning(ctx context.Context, client *bptmux.Client, name string) bool {
	process, err := client.PaneProcess(ctx, name)
	if err != nil {
		return false
	}
	pane, err := client.Capture(ctx, name)
	return err == nil && bptmux.IsAgentPane(process.Command, pane)
}

// Read only: diagnose the target without repairing books, clearing input or
// restarting a writer. Native thread evidence survives conflict reporting.
func doctorRuntimeChecks(cfg bpconfig.Config, fleet book.Fleet, selected string) []doctorCheck {
	ctx, cancel := context.WithTimeout(context.Background(), 20*time.Second)
	defer cancel()
	client := bptmux.New()
	exitEvidence := retainedLocalExitEvidence(cfg)
	if selected != "" {
		if _, ok := fleet.Agents[selected]; !ok {
			if rows, err := book.Archives(cfg.Agentbooks); err == nil {
				for _, row := range rows {
					if row.Agent.Name == selected {
						checks := []doctorCheck{{Name: "archive", Agent: selected, OK: true, Detail: "registration archived in " + row.Path + "; native history remains intact", Next: "bp restore " + selected}}
						return append(checks, localExitDoctorChecks(selected, exitEvidence[selected], true)...)
					}
				}
			}
			if checks := localExitDoctorChecks(selected, exitEvidence[selected], true); len(checks) > 0 {
				return checks
			}
			return []doctorCheck{{Name: "agent", Detail: "agent not registered: " + selected, Next: "bp book --json"}}
		}
	}
	var checks []doctorCheck
	// HasSession deliberately returns false on any tmux error. Do not turn a
	// denied socket into a reassuring "no active writer" diagnostic.
	if _, err := client.Sessions(ctx); err != nil &&
		(strings.Contains(strings.ToLower(err.Error()), "operation not permitted") || strings.Contains(strings.ToLower(err.Error()), "permission denied")) {
		return []doctorCheck{{Name: "tmux_access", Agent: selected, Detail: err.Error(),
			Next: "Run bp doctor from the outer terminal and compare access. A Codex sandbox can deny the tmux socket even while the agent is alive. Do not remove writer locks or disable the whole sandbox to repair observations; raw tmux socket access also permits host command execution."}}
	}
	for _, name := range fleet.SortedNames() {
		if selected != "" && name != selected {
			continue
		}
		entry := fleet.Agents[name]
		reports := make(map[string]localExitReport, len(exitEvidence[name])+1)
		for path, exit := range exitEvidence[name] {
			reports[path] = exit
		}
		if entry.Local != nil && !entry.IsEphemeral() {
			path := filepath.Join(filepath.Dir(entry.Local.Path), "exit.json")
			if _, exists := reports[path]; !exists {
				if exit, ok := readLocalExitReport(path); ok && localExitFailed(exit) {
					reports[path] = exit
				}
			}
		}
		hasSession := client.HasSession(ctx, name)
		running := false
		if len(reports) > 0 && hasSession && entry.Status == "open" {
			running = doctorAgentIsRunning(ctx, client, name)
		}
		for path, exit := range reports {
			laterSuccess := laterLaunchSucceeded(path, exit, entry, running)
			historical := localExitHistorical(exit, true, laterSuccess, time.Now())
			checks = append(checks, localExitDoctorCheck(name, path, exit, historical))
		}
		if !hasSession {
			if mismatch, ok := doctorNativeTitleMismatch(entry, nil, cfg.Agentbooks); ok {
				checks = append(checks, mismatch)
			}
			if selected != "" {
				checks = append(checks, doctorCheck{Name: "runtime", Agent: name, OK: true, Detail: name + ": no tmux session; historical registration is not an active writer"})
			}
			continue
		}
		probe := &app{ctx: ctx, config: cfg, tmux: client}
		if probe.ownsLocalSession(name, entry) {
			currentID := probe.resumeTmuxID(name)
			paths, _ := filepath.Glob(filepath.Join(cfg.StateDir, "local-resume", "*.json"))
			for _, path := range paths {
				data, err := os.ReadFile(path)
				if err != nil {
					continue
				}
				var claim localResumeClaim
				if json.Unmarshal(data, &claim) == nil && currentID != "" && claim.TmuxID == currentID && claim.Name != name {
					checks = append(checks, doctorCheck{Name: "resume_name/" + name, Agent: name, Related: []string{claim.Name}, Detail: "resume claim still names " + claim.Name + ": " + path, Next: "Preserve the running pane. Inspect this claim and bp book --json before correcting its Name; do not start a second writer."})
				}
			}
			for _, option := range []string{"status-left", "status-right"} {
				data, err := exec.CommandContext(ctx, client.Bin, "show-options", "-v", "-t", "="+name+":", option).Output()
				sub := "name"
				if option == "status-right" {
					sub = "bar"
				}
				text := string(data)
				if err == nil && strings.Contains(text, " "+sub+" ") && !strings.Contains(text, " "+sub+" "+quoteShell(name)) && !strings.Contains(text, "#{session_name}") {
					checks = append(checks, doctorCheck{Name: "bar_name/" + name + "/" + option, Agent: name, Detail: option + " still calls bp with another session name", Next: "bp setup refreshes BP-owned local bars without restarting the native CLI."})
				}
			}
		}
		state := book.RuntimeFor(ctx, client, fleet, name)
		if mismatch, ok := doctorNativeTitleMismatch(entry, &state, cfg.Agentbooks); ok {
			checks = append(checks, mismatch)
		}
		a := state.Activity
		if a == nil {
			continue
		}
		check := doctorCheck{Name: "runtime/" + name, Agent: name, ThreadID: a.ThreadID, OK: a.Reason == "", Detail: name + ": " + a.State, Related: a.BindingConflicts}
		if a.Reason != "" {
			check.Detail += "; " + a.Reason
			check.Next = "bp peek " + name + "; bp status --json; inspect the blocked channel with bp qstat <channel>"
		}
		if len(a.BindingConflicts) > 0 {
			check.Detail += "; model/context describe the shared thread, not separate per-agent usage"
			check.Next = "Inspect bp peek for " + strings.Join(append([]string{name}, a.BindingConflicts...), ", ") + "; choose the intended existing pane with bp con <name>. Do not kill writers or edit pins automatically."
		}
		if len(a.HistoricalBindings) > 0 {
			check.Detail += "; historical/moved registrations ignored: " + strings.Join(a.HistoricalBindings, ", ")
		}
		checks = append(checks, check)
	}
	if selected == "" {
		for name, evidence := range exitEvidence {
			if _, registered := fleet.Agents[name]; registered {
				continue
			}
			checks = append(checks, localExitDoctorChecks(name, evidence, true)...)
		}
	}
	return checks
}

func doctorNativeTitleMismatch(agent book.Agent, state *cache.State, agentbooks []string) (doctorCheck, bool) {
	value, _, err := observedNativeTitle(agent, state)
	if err != nil || value.Text == "" || value.Text == agent.Name {
		return doctorCheck{}, false
	}
	next := fmt.Sprintf("bp rename %s %s (retitle the native session to %q)", agent.Name, agent.Name, agent.Name)
	adoption, unavailable := doctorNativeTitleAdoptionHint(agent.Name, value.Text, agentbooks)
	if adoption != "" {
		next += "; " + adoption
	} else if unavailable != "" {
		next += "; " + unavailable
	}
	return doctorCheck{
		Name:    "native_title/" + agent.Name,
		Agent:   agent.Name,
		OK:      true,
		Warning: true,
		Detail:  fmt.Sprintf("bp name %q does not match native title %q", agent.Name, value.Text),
		Next:    next,
	}, true
}

func doctorNativeTitleAdoptionHint(agentName, title string, agentbooks []string) (adoption, unavailable string) {
	if !validAgentName(title) {
		return "", fmt.Sprintf(`adopt unavailable: %q is not a valid agent name`, title)
	}
	paths := book.Paths(agentbooks)
	if len(paths) == 0 {
		return "", ""
	}
	if book.RenameConflict(paths, agentName, title) == nil {
		return fmt.Sprintf("bp rename %s %s (adopt the native title as the bp name)", agentName, title), ""
	}

	// RenameConflict is the authority for whether adoption is safe. Look up the
	// owning record only to explain the conflict, without exposing its book path.
	records, err := book.Records(paths)
	if err == nil {
		for _, record := range records {
			if record.Agent.Name != title {
				continue
			}
			status := record.Agent.Status
			switch status {
			case "open", "closed", "opening":
			default:
				status = "registered"
			}
			if record.Agent.ArchivedAt != "" {
				status = "archived"
			}
			return "", fmt.Sprintf(`adopt unavailable: %q is used by agent %s (%s)`, title, record.Agent.Name, status)
		}
	}
	return "", fmt.Sprintf(`adopt unavailable: cannot verify whether %q is free`, title)
}
