package main

import (
	"encoding/json"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strings"

	"blueprint/internal/book"
	bpconfig "blueprint/internal/config"
	"blueprint/internal/release"
)

type doctorCheck struct {
	Name   string `json:"name"`
	OK     bool   `json:"ok"`
	Detail string `json:"detail"`
}

func canonicalExecutable(path string) (string, error) {
	absolute, err := filepath.Abs(path)
	if err != nil {
		return "", err
	}
	resolved, err := filepath.EvalSymlinks(absolute)
	if err != nil {
		return "", err
	}
	return filepath.Clean(resolved), nil
}

func checkExecutablePath(found, running, launcher string) (string, error) {
	foundPath, err := canonicalExecutable(found)
	if err != nil {
		return "", fmt.Errorf("resolve bp on PATH (%s): %w", found, err)
	}
	runningPath, err := canonicalExecutable(running)
	if err != nil {
		return "", fmt.Errorf("resolve running bp (%s): %w", running, err)
	}
	if foundPath == runningPath {
		return found + " (running " + running + ")", nil
	}
	// npm starts the native binary through bp.js. Its launcher overwrites this
	// environment value with its own real path before spawning the child.
	if launcher != "" {
		launcherPath, launcherErr := canonicalExecutable(launcher)
		if launcherErr == nil && foundPath == launcherPath &&
			filepath.Base(launcherPath) == "bp.js" &&
			filepath.Dir(launcherPath) == filepath.Dir(runningPath) &&
			filepath.Base(runningPath) == release.Platform() {
			return found + " (launcher for " + running + ")", nil
		}
	}
	return "", fmt.Errorf("bp on PATH resolves to %s, but the running executable is %s", foundPath, runningPath)
}

func checkShellIntegration(path string) (string, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		if os.IsNotExist(err) {
			return "", fmt.Errorf("bp shell integration is missing at %s; run bp setup", path)
		}
		return "", fmt.Errorf("read bp shell integration %s: %w", path, err)
	}
	content := string(data)
	if content == localShell {
		return "active: " + path, nil
	}
	if content == "# Generated by bp setup. Disabled; native aliases and records are preserved.\n" {
		return "disabled: " + path, nil
	}
	if strings.HasPrefix(content, "# Generated by bp setup.") {
		return "", fmt.Errorf("incomplete bp shell integration: %s; run bp setup to repair it", path)
	}
	return "", fmt.Errorf("unrecognized shell integration: %s; inspect it before running bp setup", path)
}

func doctor(cfg bpconfig.Config, configErr error, args []string) error {
	if len(args) > 1 || len(args) == 1 && args[0] != "--json" {
		return fmt.Errorf("usage: bp doctor [--json]")
	}
	if configErr == nil && cfg.InvalidConfig != "" {
		configErr = fmt.Errorf("%s", cfg.InvalidConfig)
	}
	checks := []doctorCheck{}
	add := func(name string, err error, detail string) {
		if err != nil {
			detail = err.Error()
		}
		checks = append(checks, doctorCheck{name, err == nil, detail})
	}
	add("config", configErr, cfg.Path)
	tmux, err := exec.LookPath("tmux")
	add("tmux", err, tmux)
	self, selfErr := os.Executable()
	found, err := exec.LookPath("bp")
	pathDetail := ""
	if err == nil && selfErr != nil {
		err = selfErr
	}
	if err == nil {
		pathDetail, err = checkExecutablePath(found, self, os.Getenv("BP_LAUNCHER_PATH"))
	}
	add("PATH", err, pathDetail)
	shell := filepath.Base(os.Getenv("SHELL"))
	err = nil
	if shell != "bash" && shell != "zsh" {
		err = fmt.Errorf("unsupported shell %s", shell)
	}
	add("shell", err, shell)
	if configErr == nil {
		fleet, err := book.LoadFleet(book.Paths(cfg.Agentbooks))
		add("agentbook", err, fmt.Sprintf("%d agents, coordinator %s; bp book --json shows source paths", len(fleet.Agents), fleet.Root))
	}
	home, _ := os.UserHomeDir()
	path := filepath.Join(home, ".config", "bp", "shell.sh")
	shellDetail, err := checkShellIntegration(path)
	add("shell_integration", err, shellDetail)
	clis := []string{}
	for _, name := range []string{"codex", "claude", "opencode", "hermes"} {
		if p, err := exec.LookPath(name); err == nil {
			clis = append(clis, p)
		}
	}
	err = nil
	if len(clis) == 0 {
		err = fmt.Errorf("no supported agent CLI on PATH")
	}
	add("agent_cli", err, fmt.Sprint(clis))
	ok := true
	for _, c := range checks {
		if !c.OK {
			ok = false
		}
	}
	if len(args) == 1 {
		json.NewEncoder(os.Stdout).Encode(struct {
			Version string        `json:"version"`
			OK      bool          `json:"ok"`
			Checks  []doctorCheck `json:"checks"`
		}{release.Version(), ok, checks})
	} else {
		for _, c := range checks {
			mark := "OK"
			if !c.OK {
				mark = "FAIL"
			}
			fmt.Printf("%s %-18s %s\n", mark, c.Name, c.Detail)
		}
	}
	if !ok {
		return errReported
	}
	return nil
}
