package main

import (
	bptmux "blueprint/internal/tmux"
	"context"
	"encoding/json"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"time"

	"blueprint/internal/book"
	bpconfig "blueprint/internal/config"
	"blueprint/internal/release"
)

type doctorCheck struct {
	Agent    string   `json:"agent,omitempty"`
	ThreadID string   `json:"thread_id,omitempty"`
	Related  []string `json:"related_agents,omitempty"`
	Next     string   `json:"next_step,omitempty"`
	Name     string   `json:"name"`
	OK       bool     `json:"ok"`
	Detail   string   `json:"detail"`
}

func canonicalExecutable(path string) (string, error) {
	absolute, err := filepath.Abs(path)
	if err != nil {
		return "", err
	}
	resolved, err := filepath.EvalSymlinks(absolute)
	if err != nil {
		return "", err
	}
	return filepath.Clean(resolved), nil
}

func checkExecutablePath(found, running, launcher string) (string, error) {
	foundPath, err := canonicalExecutable(found)
	if err != nil {
		return "", fmt.Errorf("resolve bp on PATH (%s): %w", found, err)
	}
	runningPath, err := canonicalExecutable(running)
	if err != nil {
		return "", fmt.Errorf("resolve running bp (%s): %w", running, err)
	}
	if foundPath == runningPath {
		return found + " (running " + running + ")", nil
	}
	// npm starts the native binary through bp.js. Its launcher overwrites this
	// environment value with its own real path before spawning the child.
	if launcher != "" {
		launcherPath, launcherErr := canonicalExecutable(launcher)
		if launcherErr == nil && foundPath == launcherPath &&
			filepath.Base(launcherPath) == "bp.js" &&
			filepath.Dir(launcherPath) == filepath.Dir(runningPath) &&
			filepath.Base(runningPath) == release.Platform() {
			return found + " (launcher for " + running + ")", nil
		}
	}
	return "", fmt.Errorf("bp on PATH resolves to %s, but the running executable is %s", foundPath, runningPath)
}

func checkShellIntegration(path string) (string, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		if os.IsNotExist(err) {
			return "", fmt.Errorf("bp shell integration is missing at %s; run bp setup", path)
		}
		return "", fmt.Errorf("read bp shell integration %s: %w", path, err)
	}
	content := string(data)
	if content == localShell {
		return "active: " + path, nil
	}
	if content == "# Generated by bp setup. Disabled; native aliases and records are preserved.\n" {
		return "disabled: " + path, nil
	}
	if strings.HasPrefix(content, "# Generated by bp setup.") {
		return "", fmt.Errorf("incomplete bp shell integration: %s; run bp setup to repair it", path)
	}
	return "", fmt.Errorf("unrecognized shell integration: %s; inspect it before running bp setup", path)
}

func doctor(cfg bpconfig.Config, configErr error, args []string) error {
	jsonOutput, agentName := false, ""
	for i := 0; i < len(args); i++ {
		switch args[i] {
		case "--json":
			jsonOutput = true
		case "--agent":
			if i+1 >= len(args) {
				return fmt.Errorf("usage: bp doctor [--agent <name>] [--json]")
			}
			i++
			agentName = args[i]
		default:
			return fmt.Errorf("usage: bp doctor [--agent <name>] [--json]")
		}
	}
	if configErr == nil && cfg.InvalidConfig != "" {
		configErr = fmt.Errorf("%s", cfg.InvalidConfig)
	}
	checks := []doctorCheck{}
	add := func(name string, err error, detail string) {
		if err != nil {
			detail = err.Error()
		}
		checks = append(checks, doctorCheck{Name: name, OK: err == nil, Detail: detail})
	}
	add("config", configErr, cfg.Path)
	tmux, err := exec.LookPath("tmux")
	add("tmux", err, tmux)
	self, selfErr := os.Executable()
	found, err := exec.LookPath("bp")
	pathDetail := ""
	if err == nil && selfErr != nil {
		err = selfErr
	}
	if err == nil {
		pathDetail, err = checkExecutablePath(found, self, os.Getenv("BP_LAUNCHER_PATH"))
	}
	add("PATH", err, pathDetail)
	shell := filepath.Base(os.Getenv("SHELL"))
	err = nil
	if shell != "bash" && shell != "zsh" {
		err = fmt.Errorf("unsupported shell %s", shell)
	}
	add("shell", err, shell)
	if configErr == nil {
		fleet, err := book.LoadFleet(book.Paths(cfg.Agentbooks))
		add("agentbook", err, fmt.Sprintf("%d agents, coordinator %s; bp book --json shows source paths", len(fleet.Agents), fleet.Root))
		if err == nil {
			checks = append(checks, doctorRuntimeChecks(cfg, fleet, agentName)...)
		}
	}
	home, _ := os.UserHomeDir()
	path := filepath.Join(home, ".config", "bp", "shell.sh")
	shellDetail, err := checkShellIntegration(path)
	add("shell_integration", err, shellDetail)
	clis := []string{}
	for _, name := range []string{"codex", "claude", "opencode", "hermes"} {
		if p, err := exec.LookPath(name); err == nil {
			clis = append(clis, p)
		}
	}
	err = nil
	if len(clis) == 0 {
		err = fmt.Errorf("no supported agent CLI on PATH")
	}
	add("agent_cli", err, fmt.Sprint(clis))
	ok := true
	for _, c := range checks {
		if !c.OK {
			ok = false
		}
	}
	if jsonOutput {
		json.NewEncoder(os.Stdout).Encode(struct {
			Version string        `json:"version"`
			OK      bool          `json:"ok"`
			Checks  []doctorCheck `json:"checks"`
		}{release.Version(), ok, checks})
	} else {
		for _, c := range checks {
			mark := "OK"
			if !c.OK {
				mark = "FAIL"
			}
			fmt.Printf("%s %-18s %s\n", mark, c.Name, c.Detail)
			if c.Next != "" {
				fmt.Printf("  next: %s\n", c.Next)
			}
		}
	}
	if !ok {
		return errReported
	}
	return nil
}

// Read only: diagnose the target without repairing books, clearing input or
// restarting a writer. Native thread evidence survives conflict reporting.
func doctorRuntimeChecks(cfg bpconfig.Config, fleet book.Fleet, selected string) []doctorCheck {
	ctx, cancel := context.WithTimeout(context.Background(), 20*time.Second)
	defer cancel()
	client := bptmux.New()
	if selected != "" {
		if _, ok := fleet.Agents[selected]; !ok {
			if rows, err := book.Archives(cfg.Agentbooks); err == nil {
				for _, row := range rows {
					if row.Agent.Name == selected {
						return []doctorCheck{{Name: "archive", Agent: selected, OK: true, Detail: "registration archived in " + row.Path + "; native history remains intact", Next: "bp restore " + selected}}
					}
				}
			}
			return []doctorCheck{{Name: "agent", Detail: "agent not registered: " + selected, Next: "bp book --json"}}
		}
	}
	var checks []doctorCheck
	for _, name := range fleet.SortedNames() {
		if selected != "" && name != selected {
			continue
		}
		entry := fleet.Agents[name]
		if entry.Local != nil {
			path := filepath.Join(filepath.Dir(entry.Local.Path), "exit.json")
			if data, err := os.ReadFile(path); err == nil {
				var exit localExitReport
				if json.Unmarshal(data, &exit) == nil && exit.Status != "0" && exit.Status != "130" && exit.Signal != "2" && exit.RoutedTo == "" {
					checks = append(checks, doctorCheck{Name: "native_exit/" + name, Agent: name, Detail: exit.Harness + " exited with status " + exit.Status, Next: "Read native exit evidence: " + path + "; do not remove writer locks or blindly retry."})
				}
			}
		}
		if !client.HasSession(ctx, name) {
			if selected != "" {
				checks = append(checks, doctorCheck{Name: "runtime", Agent: name, OK: true, Detail: name + ": no tmux session; historical registration is not an active writer"})
			}
			continue
		}
		if entry.Role == "local CLI" {
			probe := &app{ctx: ctx, config: cfg, tmux: client}
			currentID := probe.resumeTmuxID(name)
			paths, _ := filepath.Glob(filepath.Join(cfg.StateDir, "local-resume", "*.json"))
			for _, path := range paths {
				data, err := os.ReadFile(path)
				if err != nil {
					continue
				}
				var claim localResumeClaim
				if json.Unmarshal(data, &claim) == nil && currentID != "" && claim.TmuxID == currentID && claim.Name != name {
					checks = append(checks, doctorCheck{Name: "resume_name/" + name, Agent: name, Related: []string{claim.Name}, Detail: "resume claim still names " + claim.Name + ": " + path, Next: "Preserve the running pane. Inspect this claim and bp book --json before correcting its Name; do not start a second writer."})
				}
			}
			for _, option := range []string{"status-left", "status-right"} {
				data, err := exec.CommandContext(ctx, client.Bin, "show-options", "-v", "-t", "="+name+":", option).Output()
				sub := "name"
				if option == "status-right" {
					sub = "bar"
				}
				text := string(data)
				if err == nil && strings.Contains(text, " "+sub+" ") && !strings.Contains(text, " "+sub+" "+quoteShell(name)) && !strings.Contains(text, "#{session_name}") {
					checks = append(checks, doctorCheck{Name: "bar_name/" + name + "/" + option, Agent: name, Detail: option + " still calls bp with another session name", Next: "bp setup refreshes BP-owned local bars without restarting the native CLI."})
				}
			}
		}
		state := book.RuntimeFor(ctx, client, fleet, name)
		a := state.Activity
		if a == nil {
			continue
		}
		check := doctorCheck{Name: "runtime/" + name, Agent: name, ThreadID: a.ThreadID, OK: a.Reason == "", Detail: name + ": " + a.State, Related: a.BindingConflicts}
		if a.Reason != "" {
			check.Detail += "; " + a.Reason
			check.Next = "bp peek " + name + "; bp status --json; inspect the blocked channel with bp qstat <channel>"
		}
		if len(a.BindingConflicts) > 0 {
			check.Detail += "; model/context describe the shared thread, not separate per-agent usage"
			check.Next = "Inspect bp peek for " + strings.Join(append([]string{name}, a.BindingConflicts...), ", ") + "; choose the intended existing pane with bp con <name>. Do not kill writers or edit pins automatically."
		}
		if len(a.HistoricalBindings) > 0 {
			check.Detail += "; historical/moved registrations ignored: " + strings.Join(a.HistoricalBindings, ", ")
		}
		checks = append(checks, check)
	}
	return checks
}
