package main

import (
	"os"
	"path/filepath"
	"strings"
	"testing"

	"blueprint/internal/book"
	"blueprint/internal/config"
	"blueprint/internal/release"
)

func TestDoctorDeniedSocketDoesNotReportClosedWriter(t *testing.T) {
	dir := t.TempDir()
	if err := os.WriteFile(filepath.Join(dir, "tmux"), []byte("#!/bin/sh\necho 'error connecting to /tmp/tmux-1000/default (Operation not permitted)' >&2\nexit 1\n"), 0700); err != nil {
		t.Fatal(err)
	}
	t.Setenv("PATH", dir+string(os.PathListSeparator)+os.Getenv("PATH"))
	fleet := book.Fleet{Agents: map[string]book.Agent{"hypr-codex": {Name: "hypr-codex"}}}
	checks := doctorRuntimeChecks(config.Config{}, fleet, "hypr-codex")
	if len(checks) != 1 || checks[0].OK || checks[0].Name != "tmux_access" || !strings.Contains(checks[0].Detail, "Operation not permitted") {
		t.Fatalf("denied socket misdiagnosed: %+v", checks)
	}
}

func TestCheckShellIntegrationDistinguishesActiveDisabledAndBroken(t *testing.T) {
	dir := t.TempDir()
	path := filepath.Join(dir, "shell.sh")
	tests := []struct {
		name    string
		content string
		detail  string
		wantErr bool
	}{
		{name: "active", content: localShell, detail: "active: " + path},
		{name: "disabled", content: "# Generated by bp setup. Disabled; native aliases and records are preserved.\n", detail: "disabled: " + path},
		{name: "incomplete", content: "# Generated by bp setup.\n", wantErr: true},
		{name: "unrecognized", content: "user-owned shell code\n", wantErr: true},
	}
	for _, test := range tests {
		t.Run(test.name, func(t *testing.T) {
			if err := os.WriteFile(path, []byte(test.content), 0600); err != nil {
				t.Fatal(err)
			}
			detail, err := checkShellIntegration(path)
			if (err != nil) != test.wantErr {
				t.Fatalf("detail=%q error=%v", detail, err)
			}
			if !test.wantErr && detail != test.detail {
				t.Fatalf("detail=%q, want %q", detail, test.detail)
			}
		})
	}
}

func TestCheckExecutablePathAcceptsDirectAndNPMLauncherPaths(t *testing.T) {
	dir := t.TempDir()
	running := filepath.Join(dir, release.Platform())
	launcher := filepath.Join(dir, "bp.js")
	other := filepath.Join(dir, "other-bp")
	for _, path := range []string{running, launcher, other} {
		if err := os.WriteFile(path, []byte(path), 0700); err != nil {
			t.Fatal(err)
		}
	}
	direct := filepath.Join(dir, "bp-direct")
	if err := os.Symlink(running, direct); err != nil {
		t.Fatal(err)
	}
	if detail, err := checkExecutablePath(direct, running, ""); err != nil || !strings.Contains(detail, "running") {
		t.Fatalf("direct detail=%q error=%v", detail, err)
	}
	npm := filepath.Join(dir, "bp-npm")
	if err := os.Symlink(launcher, npm); err != nil {
		t.Fatal(err)
	}
	if detail, err := checkExecutablePath(npm, running, launcher); err != nil || !strings.Contains(detail, "launcher") {
		t.Fatalf("npm detail=%q error=%v", detail, err)
	}
	if _, err := checkExecutablePath(other, running, ""); err == nil {
		t.Fatal("mismatched bp executable passed PATH check")
	}
}
