package main

import (
	bpconfig "blueprint/internal/config"
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

const localShell = `# Generated by bp setup. Re-source this file to enable local agent sessions.
case ":$PATH:" in
  *":$HOME/.local/bin:"*) ;;
  *) export PATH="$HOME/.local/bin:$PATH" ;;
esac
_bp_agent() {
  if [ -n "${TMUX:-}" ] || [ -n "${BP_SESSION:-}" ] || [ ! -t 0 ] || [ ! -t 1 ] || ! command -v bp >/dev/null 2>&1; then
    command "$@"
  else
    command bp run "$@"
  fi
}
# Keep aliases intact: e.g. claude='claude --my-options' expands first,
# then calls this function with those options. The function keyword avoids
# expanding an existing alias while defining the function in Bash and Zsh.
# A user's existing function takes precedence over bp integration.
_bp_install_function() {
  typeset -f "$1" >/dev/null 2>&1 && return 0
  eval 'function '"$1"' { _bp_agent '"$1"' "$@"; }'
}
_bp_install_function codex
_bp_install_function claude
_bp_install_function opencode
_bp_install_function hermes
unset -f _bp_install_function
`

func (a *app) localSetup(args []string) error {
	if len(args) == 1 && args[0] == "--check" {
		return a.setupCheck()
	}
	if len(args) == 1 && args[0] == "--disable" {
		return a.disableSetup()
	}

	if a.config.InvalidConfig != "" {
		return fmt.Errorf("fix the existing config before setup: %s", a.config.InvalidConfig)
	}
	shell := filepath.Base(os.Getenv("SHELL"))
	if len(args) == 2 && args[0] == "--shell" {
		shell = args[1]
	} else if len(args) != 0 {
		return fmt.Errorf("usage: bp setup [--shell bash|zsh]")
	}
	if shell != "bash" && shell != "zsh" {
		return fmt.Errorf("shell %q is not supported; use bp setup --shell bash or --shell zsh", shell)
	}
	configPath, err := bpconfig.InitYAML(a.config.Home)
	if err != nil {
		return err
	}
	if err := a.initLocalBook(); err != nil {
		return err
	}
	home, err := os.UserHomeDir()
	if err != nil {
		return err
	}
	dir := filepath.Join(home, ".config", "bp")
	if err := os.MkdirAll(dir, 0700); err != nil {
		return err
	}
	if err := os.WriteFile(filepath.Join(dir, "shell.sh"), []byte(localShell), 0600); err != nil {
		return err
	}
	files := []string{filepath.Join(home, ".zshrc")}
	if shell == "zsh" && os.Getenv("ZDOTDIR") != "" {
		files = []string{filepath.Join(os.Getenv("ZDOTDIR"), ".zshrc")}
	}
	if shell == "bash" {
		files = []string{filepath.Join(home, ".bashrc")}
		// Bash login shells read the first existing profile in this order.
		profile := filepath.Join(home, ".bash_profile")
		for _, name := range []string{".bash_profile", ".bash_login", ".profile"} {
			path := filepath.Join(home, name)
			if _, err := os.Stat(path); err == nil {
				profile = path
				break
			}
		}
		files = append(files, profile)
	}
	line := `[ -r "$HOME/.config/bp/shell.sh" ] && . "$HOME/.config/bp/shell.sh" # bp local agents`
	for _, path := range files {
		data, err := os.ReadFile(path)
		if err != nil && !os.IsNotExist(err) {
			return err
		}
		if strings.Contains(string(data), line) {
			continue
		}
		if err := os.MkdirAll(filepath.Dir(path), 0700); err != nil {
			return err
		}
		if len(data) > 0 {
			backup, err := os.CreateTemp(filepath.Dir(path), filepath.Base(path)+".before-bp-*")
			if err != nil {
				return err
			}
			_, writeErr := backup.Write(data)
			closeErr := backup.Close()
			if writeErr != nil {
				return writeErr
			}
			if closeErr != nil {
				return closeErr
			}
		}
		f, err := os.OpenFile(path, os.O_WRONLY|os.O_CREATE|os.O_APPEND, 0600)
		if err != nil {
			return err
		}
		_, writeErr := fmt.Fprintln(f, "\n"+line)
		closeErr := f.Close()
		if writeErr != nil {
			return writeErr
		}
		if closeErr != nil {
			return closeErr
		}
	}
	if err := a.refreshLocalBars(); err != nil {
		return err
	}
	fmt.Fprintln(a.out, "bp local setup ready. Open a new terminal, or run: . \"$HOME/.config/bp/shell.sh\"")
	fmt.Fprintln(a.out, "bp wrappers ready; existing aliases and functions are preserved; 'command codex' bypasses the wrapper.")
	fmt.Fprintf(a.out, "Settings: %s (check with: bp config check)\n", configPath)
	return nil
}
