package harness

// The four harnesses bp drives today. Facts are checked against the binaries
// installed on the reference host and against bp's own measured behavior; the
// Checked field names the versions.

var _ = register(&Descriptor{
	Kind: Claude, Name: "Claude Code", Vendor: "Anthropic", Class: ClassCLI,
	Checked: "2.1.295, 2026-10-09", License: "proprietary",
	Install:  []string{"curl -fsSL https://claude.ai/install.sh | bash", "npm install -g @anthropic-ai/claude-code"},
	Login:    "Claude subscription OAuth (/login) or ANTHROPIC_API_KEY",
	Binaries: []string{"claude"}, Wrappers: []string{"node", "bwrap"},
	Interactive: true,
	Headless:    "claude -p <prompt> [--output-format text|json|stream-json] [--input-format stream-json]",
	Resume:      Resume{Continue: "claude --continue", ByID: "claude --resume <session-id>", IDFormat: "UUID"},
	Naming:      "claude --name <name>; /rename <name> (custom-title record)",
	MCP: MCP{Client: true, Config: []string{"~/.claude.json (user, local)", ".mcp.json (project)", "claude --mcp-config <file> (per launch)"},
		Format: "json", Transports: []string{"stdio", "http", "sse"}, AddCommand: "claude mcp add <name> -- <command>"},
	Hooks: Hooks{Config: "~/.claude/settings.json, .claude/settings.json, .claude/settings.local.json; per launch: --settings <file-or-json>",
		Events:    []string{"SessionStart", "UserPromptSubmit", "PreToolUse", "PostToolUse", "Notification", "Stop", "SubagentStop", "PreCompact", "SessionEnd"},
		Inject:    "UserPromptSubmit/SessionStart: hookSpecificOutput.additionalContext; Stop: {\"decision\":\"block\",\"reason\":...} continues the turn with the reason",
		PerLaunch: "--settings layer (bp already passes one to the sessions it launches)"},
	Push: "none for a local TUI session (Remote Control links a claude.ai session; channels are research preview)",
	Transcripts: Transcripts{Root: "$CLAUDE_CONFIG_DIR/projects/<munged-cwd>/<session-id>.jsonl (default ~/.claude/projects)", Format: "jsonl",
		Records: []string{"user", "assistant", "system/turn_duration", "system/compact_boundary", "system/stop_hook_summary", "attachment/hook_additional_context", "custom-title", "continued-in"}},
	Compaction: Compaction{Manual: "/compact [instructions]", Auto: "on by default near the context limit",
		Markers: []string{`system subtype "compact_boundary" (compactMetadata.trigger manual|auto, postTokens)`, "user record with isCompactSummary=true", "<local-command-stdout>Compacted (ctrl+o to see full summary)</local-command-stdout>"},
		Event:   "PreCompact hook; SessionStart hook with source=compact afterwards"},
	Screen: ScreenFacts{Busy: "spinner row above the composer: one symbol glyph, one word ending in an ellipsis, optional (timer ...) counter; none while a long answer streams",
		Idle:   "bordered composer box with the agent name in the top border; footer below shows -- INSERT -- / bypass permissions",
		Paste:  "bracketed paste; large or multi-line pastes become [Pasted text #N +M lines]; trailing image paths turn into [Image #N]",
		Submit: "Enter", Dialogs: "Enter to select · Esc to cancel footers; trust and resume pickers at start-up"},
	Usage:        "status line JSON (context_window, current_usage); assistant message.usage in the transcript; /context, /cost",
	Instructions: "CLAUDE.md (user, project, local); skills in ~/.claude/skills/<name>/SKILL.md",
	Terms:        "Consumer subscription use is governed by Anthropic's Consumer Terms and usage policy; automated or programmatic access is meant for the API / Agent SDK. bp drives the user's own interactive client at human-like turn boundaries and never shares credentials.",
	Delivery:     []Path{PathHooks, PathTerminal, PathPull},
	Behaviors: map[Behavior]Status{
		BReceiveAtBoundary:  {Supported, PathHooks, "Stop and UserPromptSubmit hooks claim queued messages; the terminal path covers an agent idle between turns"},
		BNeverInterrupt:     {Supported, PathTerminal, "busy spinner + transcript TurnOpen probe; hooks run only at boundaries"},
		BConfirmDelivery:    {Supported, "", "hook claims close as delivered (hook); pastes are confirmed by the transcript witness"},
		BSurviveCompaction:  {Supported, PathHooks, "queue and spool are on disk; SessionStart(source=compact) carries queued messages"},
		BResume:             {Supported, "", "bp open --resume follows customTitle and continued-in chains"},
		BReportUsage:        {Supported, "", "status-line observation and transcript usage"},
		BRenameTitle:        {Supported, "", "--name at launch, /rename after Remote Control"},
		BIdentityAfterReset: {Supported, PathHooks, "SessionStart(source=compact|clear) restates the bp identity"},
	},
	Sources: []string{"claude --help (2.1.295)", "https://docs.anthropic.com/en/docs/claude-code/hooks", "internal/tmux (measured signatures)", "real claude -p run with Stop/UserPromptSubmit hooks, 2026-10-09"},
})

var _ = register(&Descriptor{
	Kind: Codex, Name: "Codex CLI", Vendor: "OpenAI", Class: ClassCLI,
	Checked: "codex-cli 0.162.0, 2026-10-09", License: "Apache-2.0",
	Install:  []string{"npm install -g @openai/codex", "brew install codex"},
	Login:    "ChatGPT account OAuth (codex login) or OPENAI_API_KEY",
	Binaries: []string{"codex"}, Wrappers: []string{"node", "bwrap"},
	Interactive: true,
	Headless:    "codex exec <prompt> [--json] [resume <id>]",
	Resume:      Resume{Continue: "codex resume --last", ByID: "codex resume <thread-uuid|name>", IDFormat: "UUID"},
	Naming:      "session_index.jsonl thread_name rows (bp writes them)",
	MCP: MCP{Client: true, Config: []string{"$CODEX_HOME/config.toml [mcp_servers.<name>] (default ~/.codex)", "-c mcp_servers.<name>.command=... (per launch)"},
		Format: "toml", Transports: []string{"stdio", "streamable-http"}, AddCommand: "codex mcp add <name> -- <command>"},
	Hooks: Hooks{Config: "~/.codex/hooks.json, <repo>/.codex/hooks.json (trusted projects), [hooks] in config.toml, plugin hooks/hooks.json; on by default; each hook needs persisted trust (/hooks) or --dangerously-bypass-hook-trust",
		Events:    []string{"SessionStart", "SessionEnd", "UserPromptSubmit", "PreToolUse", "PostToolUse", "PermissionRequest", "PreCompact", "PostCompact", "Stop", "SubagentStart", "SubagentStop", "Interrupt"},
		Inject:    "Claude-compatible: additionalContext from SessionStart (source startup|resume|clear|compact), UserPromptSubmit, Pre/PostToolUse; Stop {\"decision\":\"block\",\"reason\":...} continues the turn; PostCompact cannot inject",
		PerLaunch: "unverified: -c overrides of [hooks] plus --dangerously-bypass-hook-trust"},
	Push: "app-server JSON-RPC (codex app-server; turn/start on a thread); codex queue --thread <id> --message <text> (app-server thread/queue/add; runs after the current turn; an unloaded thread waits until resumed)",
	Transcripts: Transcripts{Root: "$CODEX_HOME/sessions/YYYY/MM/DD/rollout-*-<uuid>.jsonl", Format: "jsonl",
		Records: []string{"session_meta", "turn_context", "event_msg/token_count", "event_msg/task_started", "event_msg/task_complete", "event_msg/turn_aborted", "response_item/message", "compacted", "event_msg/context_compacted"}},
	Compaction: Compaction{Manual: "/compact", Auto: "model_auto_compact_token_limit",
		Markers: []string{`record type "compacted"`, `event_msg type "context_compacted"`}, Event: "PreCompact / PostCompact hooks"},
	Screen: ScreenFacts{Busy: "• Working (Ns • esc to interrupt) row above the composer; busy composer footer 'tab to queue message'",
		Idle:   "› Ask Codex ... placeholder; footer '<model> <effort> · /abs/cwd' in every state",
		Paste:  "bracketed paste; >~1024 chars become [Pasted Content N chars]; first Enter expands, second submits",
		Submit: "Enter when idle; Tab queues into Codex's own queue while busy", Dialogs: "trust modal, start-up navigation menu, / and ? search prompts"},
	Usage:        "event_msg/token_count (last_token_usage, model_context_window); app-server thread status",
	Instructions: "AGENTS.md (CODEX_HOME and project); skills in $CODEX_HOME/skills/<name>/SKILL.md",
	Terms:        "ChatGPT plan usage is governed by OpenAI's Terms of Use and usage policies; programmatic use is offered through codex exec, the SDK and app-server.",
	Delivery:     []Path{PathPush, PathTerminal, PathHooks, PathPull},
	Behaviors: map[Behavior]Status{
		BReceiveAtBoundary:  {Supported, PathTerminal, "paste at boundary; Tab into the native queue when busy; app-server for remote threads"},
		BNeverInterrupt:     {Supported, PathTerminal, "Working row + app-server status + rollout turn state"},
		BConfirmDelivery:    {Supported, "", "rollout response_item/message witness"},
		BSurviveCompaction:  {Partial, "", "queue is on disk and rollouts are append-only so the witness survives; no identity restatement yet"},
		BResume:             {Supported, "", "identity thread pin + codex resume <uuid>"},
		BReportUsage:        {Supported, "", "token_count records"},
		BRenameTitle:        {Supported, "", "session_index.jsonl thread_name"},
		BIdentityAfterReset: {Planned, PathHooks, "PostCompact / SessionStart hooks or a queued identity note after a compacted record"},
	},
	Sources: []string{"codex --help, codex queue --help, codex features list (0.162.0)", "strings of the 0.162 binary (hook events)", "https://developers.openai.com/codex/hooks", "openai/codex PR #39092 (codex queue)", "internal/cache/codex.go, internal/tmux/codex.go"},
})

var _ = register(&Descriptor{
	Kind: Hermes, Name: "Hermes Agent", Vendor: "Nous Research", Class: ClassCLI,
	Checked: "v0.20.5 (2026.8.19), 2026-10-09", License: "MIT",
	Install:  []string{"curl -fsSL https://raw.githubusercontent.com/NousResearch/hermes-agent/main/scripts/install.sh | bash"},
	Login:    "provider API keys or OAuth per provider (hermes model / hermes login)",
	Binaries: []string{"hermes"}, Wrappers: []string{"python", "python3"},
	Interactive: true,
	Headless:    "hermes chat -q <prompt>",
	Resume:      Resume{Continue: "hermes --continue", ByID: "hermes --resume <session-id>"},
	MCP:         MCP{Client: true, Config: []string{"~/.hermes/config.yaml mcp_servers:"}, Format: "yaml", Transports: []string{"stdio", "http"}},
	Hooks: Hooks{Config: "~/.hermes/config.yaml hooks: (shell hooks); ~/.hermes/plugins/<name>/ (Python plugins)",
		Events:    []string{"pre_llm_call", "post_llm_call", "pre_tool_call", "post_tool_call", "pre_verify", "on_session_start", "on_session_end", "on_session_reset", "subagent_stop"},
		Inject:    `pre_llm_call: stdout {"context": "..."} is appended to the turn's user message; pre_verify: {"decision":"block","reason":...} keeps the agent going (only when code was edited)`,
		PerLaunch: "none: hooks live in config.yaml and need first-use consent (--accept-hooks / HERMES_ACCEPT_HOOKS=1)"},
	Push:        "ACP server (hermes acp); API server and webhooks (gateway); plugins can ctx.inject_message",
	Transcripts: Transcripts{Root: "~/.hermes/state.db (SQLite: sessions, messages)", Format: "sqlite"},
	Compaction: Compaction{Manual: "/compress", Auto: "context compression before each turn when near the limit",
		Markers: []string{"compression rotates the session id (parent_session_id chain)"}, Event: "pre_llm_call fires after compression"},
	Screen: ScreenFacts{Busy: "⚕ in front of the prompt marker (⚕ ❯ msg=interrupt · /queue · /bg · /steer)",
		Idle: "❯ Ask anything, or type / for commands…", Paste: "bracketed paste", Submit: "Enter; Enter on a busy pane interrupts the turn",
		Dialogs: "⚠ ❯ composer and 'to select ... to confirm' hints"},
	Usage:        "session_model_usage table; status row shows context percent",
	Instructions: "AGENTS.md / SOUL.md / .hermes.md context files; skills in ~/.hermes/skills",
	Terms:        "open source; provider terms apply",
	Delivery:     []Path{PathTerminal, PathHooks, PathPush, PathPull},
	Behaviors: map[Behavior]Status{
		BReceiveAtBoundary:  {Supported, PathTerminal, "paste only when the caduceus is absent"},
		BNeverInterrupt:     {Supported, PathTerminal, "busy Hermes refuses even forced delivery (Enter would cancel the turn)"},
		BConfirmDelivery:    {Partial, "", "no transcript reader (SQLite); deliveries stay unverified"},
		BSurviveCompaction:  {Partial, "", "queue is on disk; compaction is not observed"},
		BResume:             {Partial, "", "launch only; no session pin"},
		BReportUsage:        {Partial, "", "external usage snapshot script"},
		BRenameTitle:        {Unknown, "", ""},
		BIdentityAfterReset: {Planned, PathHooks, "pre_llm_call hook restates identity when the session id rotates"},
	},
	Sources: []string{"hermes --version", "/usr/local/lib/hermes-agent/website/docs/user-guide/features/hooks.md", "internal/tmux/hermes.go"},
})

var _ = register(&Descriptor{
	Kind: OpenCode, Name: "OpenCode", Vendor: "SST / Anomaly", Class: ClassCLI,
	Checked: "1.18.32, 2026-10-09", License: "MIT",
	Install:     []string{"curl -fsSL https://opencode.ai/install | bash", "npm install -g opencode-ai"},
	Login:       "opencode auth login (provider OAuth or API keys); OpenCode Zen",
	Binaries:    []string{"opencode"},
	Interactive: true,
	Headless:    "opencode run <message> [--format json]",
	Resume:      Resume{Continue: "opencode --continue", ByID: "opencode --session <id>"},
	Naming:      "opencode run --title <title>; PATCH /session/:id",
	MCP:         MCP{Client: true, Config: []string{"~/.config/opencode/opencode.json mcp:", "opencode.json (project)"}, Format: "json", Transports: []string{"local (stdio)", "remote (http)"}},
	Hooks: Hooks{Config: "JS/TS plugins in ~/.config/opencode/plugins/ or .opencode/plugins/",
		Events: []string{"session.idle", "session.status", "session.compacted", "session.created", "message.updated", "tool.execute.before", "tool.execute.after", "experimental.session.compacting"},
		Inject: "a plugin calls the SDK client (session.prompt / tui.appendPrompt); experimental.session.compacting adds output.context to the compaction summary"},
	Push:        "opencode serve HTTP API: POST /session/:id/prompt_async, /tui/append-prompt, /tui/submit-prompt; GET /event (SSE); opencode acp",
	Transcripts: Transcripts{Root: "~/.local/share/opencode/opencode.db (SQLite: session, message, part, event)", Format: "sqlite"},
	Compaction: Compaction{Manual: "/compact (alias /summarize), POST /session/:id/summarize", Auto: "automatic when the context overflows",
		Event: "session.compacted plugin event; experimental.session.compacting hook"},
	Screen: ScreenFacts{Busy: "progress dots with 'esc interrupt'", Idle: "┃ rail composer, 'Ask anything...' placeholder, ╹▀▀▀ bottom edge",
		Paste: "[Pasted ~N lines] chip", Submit: "Enter", Dialogs: "permission prompts"},
	Usage:        "opencode stats; step-finish parts carry tokens",
	Instructions: "AGENTS.md (/init creates it)",
	Terms:        "open source; provider terms apply",
	Delivery:     []Path{PathTerminal, PathPush, PathHooks, PathPull},
	Behaviors: map[Behavior]Status{
		BReceiveAtBoundary:  {Supported, PathTerminal, ""},
		BNeverInterrupt:     {Supported, PathTerminal, "esc interrupt row"},
		BConfirmDelivery:    {Partial, "", "no transcript reader (SQLite); deliveries stay unverified"},
		BSurviveCompaction:  {Partial, "", "queue is on disk; compaction is not observed"},
		BResume:             {Partial, "", ""},
		BReportUsage:        {Unknown, "", ""},
		BRenameTitle:        {Unknown, "", ""},
		BIdentityAfterReset: {Planned, PathHooks, "plugin: experimental.session.compacting adds the bp identity to the summary"},
	},
	Sources: []string{"opencode --help (1.18.32)", "https://opencode.ai/docs/plugins", "https://opencode.ai/docs/server", "internal/tmux/opencode.go"},
})
