package main

import (
	"fmt"
	"os"
	"strings"
	"unicode"
)

// writeTables generates crates/bp-tmux/src/screen/unicode_tables.rs: Go's
// unicode.Mn and unicode.Me range tables, which composerRuneWidth consults.
// Generating them from Go keeps the Rust width table on Go's Unicode version.
func writeTables(path string) {
	var ranges [][2]rune
	for _, table := range []*unicode.RangeTable{unicode.Mn, unicode.Me} {
		for _, r := range table.R16 {
			for lo := rune(r.Lo); lo <= rune(r.Hi); lo += rune(r.Stride) {
				ranges = appendRune(ranges, lo)
				if r.Stride == 1 {
					ranges = appendRange(ranges, rune(r.Lo), rune(r.Hi))
					break
				}
			}
		}
		for _, r := range table.R32 {
			for lo := rune(r.Lo); lo <= rune(r.Hi); lo += rune(r.Stride) {
				ranges = appendRune(ranges, lo)
				if r.Stride == 1 {
					ranges = appendRange(ranges, rune(r.Lo), rune(r.Hi))
					break
				}
			}
		}
	}
	ranges = normalize(ranges)
	var b strings.Builder
	fmt.Fprintf(&b, "//! Port of Go's `unicode.Mn` and `unicode.Me` tables (Unicode %s), used by\n", unicode.Version)
	b.WriteString("//! `composerRuneWidth`. Generated by `go run ./tools/goldenexport/tmux -tables`;\n")
	b.WriteString("//! do not edit by hand.\n\n")
	b.WriteString("/// Sorted, non-overlapping inclusive ranges of Mn and Me code points.\n")
	b.WriteString("const MARK_NONSPACING_OR_ENCLOSING: &[(u32, u32)] = &[\n")
	for _, r := range ranges {
		fmt.Fprintf(&b, "    (0x%04X, 0x%04X),\n", r[0], r[1])
	}
	b.WriteString("];\n\n")
	b.WriteString("/// `unicode.Is(unicode.Mn, r) || unicode.Is(unicode.Me, r)`.\n")
	b.WriteString("pub(crate) fn is_mark_nonspacing_or_enclosing(c: char) -> bool {\n")
	b.WriteString("    let r = c as u32;\n")
	b.WriteString("    MARK_NONSPACING_OR_ENCLOSING\n")
	b.WriteString("        .binary_search_by(|&(lo, hi)| {\n")
	b.WriteString("            if hi < r {\n")
	b.WriteString("                std::cmp::Ordering::Less\n")
	b.WriteString("            } else if lo > r {\n")
	b.WriteString("                std::cmp::Ordering::Greater\n")
	b.WriteString("            } else {\n")
	b.WriteString("                std::cmp::Ordering::Equal\n")
	b.WriteString("            }\n")
	b.WriteString("        })\n")
	b.WriteString("        .is_ok()\n")
	b.WriteString("}\n")
	if err := os.WriteFile(path, []byte(b.String()), 0o644); err != nil {
		panic(err)
	}
}

func appendRune(ranges [][2]rune, r rune) [][2]rune { return append(ranges, [2]rune{r, r}) }

func appendRange(ranges [][2]rune, lo, hi rune) [][2]rune { return append(ranges, [2]rune{lo, hi}) }

// normalize sorts and merges overlapping or adjacent ranges.
func normalize(ranges [][2]rune) [][2]rune {
	for i := 1; i < len(ranges); i++ {
		for j := i; j > 0 && ranges[j][0] < ranges[j-1][0]; j-- {
			ranges[j], ranges[j-1] = ranges[j-1], ranges[j]
		}
	}
	var out [][2]rune
	for _, r := range ranges {
		if n := len(out); n > 0 && r[0] <= out[n-1][1]+1 {
			if r[1] > out[n-1][1] {
				out[n-1][1] = r[1]
			}
			continue
		}
		out = append(out, r)
	}
	return out
}
