package modules

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"blueprint/internal/safefile"
)

// compactionHooksConflicts mirrors guardHooksConflicts: the compaction-hooks
// module answers a harness hook by resolving the calling tmux pane to an
// agent name (the same pane-based identity bp _hook claude already uses), so
// it is useless on an agent started outside bp.
func compactionHooksConflicts(env Env) []string {
	if !EnabledIn(env.Config, Sessions) {
		return []string{"sessions is off: only agents started with bp run or bp open resolve to an agent name; a plain opencode or hermes session would call the hook as nobody"}
	}
	return nil
}

// opencodePluginMarker starts the plugin file the compaction-hooks module
// writes; undo checks it the same way the sessions module's shell.sh does.
const opencodePluginMarker = "// Generated by bp (compaction-hooks module)."

// hermesHookMarker starts the shell script the compaction-hooks module writes
// for Hermes's pre_llm_call hook.
const hermesHookMarker = "# Generated by bp (compaction-hooks module)."

// OpenCodePluginPath is the global OpenCode plugin directory entry the
// compaction-hooks module writes (docs/security/compaction-hooks-module.md,
// "OpenCode": ~/.config/opencode/plugins/, confirmed against the installed
// @opencode-ai/plugin and @opencode-ai/sdk type definitions and
// https://opencode.ai/docs/plugins).
func OpenCodePluginPath(userHome string) string {
	return filepath.Join(userHome, ".config", "opencode", "plugins", "bp-compaction.js")
}

// HermesHookScriptPath is the shell script the compaction-hooks module writes
// for Hermes's pre_llm_call shell hook (~/.hermes/agent-hooks/ by convention;
// docs/security/compaction-hooks-module.md, "Hermes").
func HermesHookScriptPath(userHome string) string {
	return filepath.Join(userHome, ".hermes", "agent-hooks", "bp-compaction.sh")
}

// HermesConfigPath is the Hermes config file the module adds one
// hooks.pre_llm_call entry to.
func HermesConfigPath(userHome string) string {
	return filepath.Join(userHome, ".hermes", "config.yaml")
}

// opencodePluginSource is the OpenCode plugin bp installs. It watches for the
// "session.compacted" event (internal/harness/core.go, OpenCode Hooks.Events;
// confirmed in the installed @opencode-ai/sdk type definitions —
// EventSessionCompacted{type: "session.compacted", properties: {sessionID}})
// and, on it, shells out to `bp _hook opencode` for the identity note and
// injects it with client.session.promptAsync, the real SDK client method
// (confirmed in @opencode-ai/sdk/dist/gen/sdk.gen.d.ts: Session.promptAsync,
// SessionPromptAsyncData{path:{id}, body:{parts, noReply}}) with noReply so
// the note never starts a new agent turn. A broken hook (bp missing, bad
// JSON, a rejected request) must never break the agent, so every failure is
// swallowed.
func opencodePluginSource(bpPath string) string {
	encodedPath, _ := json.Marshal(bpPath)
	return opencodePluginMarker + ` Restates the bp identity to this OpenCode
// session after a context compaction. Safe to delete; bp rewrites it on
// ` + "`bp enable compaction-hooks`" + ` and removes it on ` + "`bp disable compaction-hooks`" + `.
const BP_PATH = ` + string(encodedPath) + `

// Named export, not a default export: the OpenCode plugin loader discovers
// plugin functions by their exports (https://opencode.ai/docs/plugins), and
// every documented example uses a named const, never export default.
export const BpCompactionPlugin = async ({ client }) => {
  return {
    event: async ({ event }) => {
      if (event.type !== "session.compacted") return
      let note
      try {
        const { execFileSync } = await import("node:child_process")
        const out = execFileSync(BP_PATH, ["_hook", "opencode"], { encoding: "utf8", timeout: 5000 })
        note = JSON.parse(out).note
      } catch (_err) {
        return
      }
      if (!note) return
      try {
        await client.session.promptAsync({
          path: { id: event.properties.sessionID },
          body: { parts: [{ type: "text", text: note, synthetic: true }], noReply: true },
        })
      } catch (_err) {
        // A broken plugin must never break the agent.
      }
    },
  }
}
`
}

// hermesHookScript is the shell hook bp installs for Hermes's pre_llm_call
// event, the only one that can inject LLM context (the vendor's shell-hooks
// doc, "pre_llm_call" and "Shell Hooks" sections). It forwards the hook's
// JSON stdin payload to bp unchanged; bp decides whether this turn is the
// first one after a compaction fork and, only then, answers with
// {"context": ...}. Any other turn gets no output, which Hermes treats as a
// silent no-op.
func hermesHookScript(bpPath string) string {
	return "#!/bin/sh\n" + hermesHookMarker + ` Forwards the pre_llm_call hook
# payload to bp, which restates the bp identity after a compaction fork and
# emits nothing otherwise. Safe to delete; bp rewrites it on
# ` + "`bp enable compaction-hooks`" + ` and removes it on ` + "`bp disable compaction-hooks`" + `.
exec ` + shellQuote(bpPath) + ` _hook hermes
`
}

// shellQuote wraps value in single quotes for a POSIX sh command line,
// escaping any single quote it contains. internal/modules cannot import
// cmd/bp's quoteShell, so this is its own small copy of the same idiom.
func shellQuote(value string) string {
	return "'" + strings.ReplaceAll(value, "'", `'\''`) + "'"
}

// applyCompactionHooks installs the OpenCode plugin and the Hermes shell hook
// (script file plus its hooks.pre_llm_call entry in config.yaml). Both
// artifacts are written regardless of whether that harness is installed on
// this host: an OpenCode plugin file nothing ever loads, or a Hermes hook
// entry nothing ever runs, is inert. Enabling again refreshes bytes bp still
// owns (the journal's SHA-256 check); it never touches a file the user has
// since edited.
func applyCompactionHooks(env Env, journal *Journal) error {
	if env.UserHome == "" {
		return fmt.Errorf("no home directory")
	}
	self, err := os.Executable()
	if err != nil {
		return err
	}
	if err := writeOwnedFile(journal, OpenCodePluginPath(env.UserHome), opencodePluginSource(self), opencodePluginMarker, 0600); err != nil {
		return err
	}
	scriptPath := HermesHookScriptPath(env.UserHome)
	if err := writeOwnedFile(journal, scriptPath, hermesHookScript(self), hermesHookMarker, 0700); err != nil {
		return err
	}
	change, err := AddYAMLEntry(HermesConfigPath(env.UserHome), "hooks.pre_llm_call", map[string]any{
		"command": scriptPath,
		"timeout": 5,
	})
	if err != nil {
		return fmt.Errorf("hermes config.yaml: %w", err)
	}
	if change != nil {
		journal.Record(*change)
	}
	return nil
}

// writeOwnedFile writes a whole file bp owns (KindFile: undo removes it only
// while the marker is still there, or the hash still matches), the same
// idiom sessions.go uses for shell.sh.
func writeOwnedFile(journal *Journal, path, content, marker string, mode os.FileMode) error {
	change := Change{Kind: KindFile, Path: path, Marker: marker, SHA256: fileSHA256([]byte(content))}
	if journal.DryRun() {
		journal.Record(change)
		return nil
	}
	_, snap, err := safefile.Read(path)
	if err != nil {
		return err
	}
	if err := safefile.Replace(snap, []byte(content), mode); err != nil {
		return err
	}
	journal.Record(change)
	return nil
}
