package modules

import (
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

// ShellMarker starts the shell integration file; undo removes the file only
// while it still carries this text (bp setup --disable keeps it too).
const ShellMarker = "# Generated by bp setup."

// RCLine is the one line the sessions module adds to the user's shell rc.
const RCLine = `[ -r "$HOME/.config/bp/shell.sh" ] && . "$HOME/.config/bp/shell.sh" # bp local agents`

// LocalShell is the shell integration file the sessions module writes.
const LocalShell = ShellMarker + ` Re-source this file to enable local agent sessions.
case ":$PATH:" in
  *":$HOME/.local/bin:"*) ;;
  *) export PATH="$HOME/.local/bin:$PATH" ;;
esac
_bp_agent() {
  if [ -n "${TMUX:-}" ] || [ -n "${BP_SESSION:-}" ] || [ ! -t 0 ] || [ ! -t 1 ] || ! command -v bp >/dev/null 2>&1; then
    command "$@"
  else
    command bp run "$@"
  fi
}
# Keep aliases intact: e.g. claude='claude --my-options' expands first,
# then calls this function with those options. The function keyword avoids
# expanding an existing alias while defining the function in Bash and Zsh.
# A user's existing function takes precedence over bp integration.
_bp_install_function() {
  typeset -f "$1" >/dev/null 2>&1 && return 0
  eval 'function '"$1"' { _bp_agent '"$1"' "$@"; }'
}
_bp_install_function codex
_bp_install_function claude
_bp_install_function opencode
_bp_install_function hermes
unset -f _bp_install_function
`

// CompatibilityWrappers adds the optional lush/rush helpers.
const CompatibilityWrappers = `# Optional compatibility names. Existing aliases and functions always win.
_bp_install_compat() {
  typeset -f "$1" >/dev/null 2>&1 && return 0
  alias "$1" >/dev/null 2>&1 && return 0
  eval 'function '"$1"' { command bp '"$2"' "$@"; }'
}
_bp_install_compat lush attach
_bp_install_compat rush shell
unset -f _bp_install_compat
`

// ShellPath is the shell integration file the rc line sources.
func ShellPath(userHome string) string {
	return filepath.Join(userHome, ".config", "bp", "shell.sh")
}

// RCFiles lists the rc files the sessions module edits for a shell.
func RCFiles(env Env) ([]string, error) {
	shell := env.Shell
	if shell == "" {
		shell = filepath.Base(env.getenv("SHELL"))
	}
	home := env.UserHome
	switch shell {
	case "zsh":
		if dir := env.getenv("ZDOTDIR"); dir != "" {
			return []string{filepath.Join(dir, ".zshrc")}, nil
		}
		return []string{filepath.Join(home, ".zshrc")}, nil
	case "bash":
		files := []string{filepath.Join(home, ".bashrc")}
		// Bash login shells read the first existing profile in this order.
		profile := filepath.Join(home, ".bash_profile")
		for _, name := range []string{".bash_profile", ".bash_login", ".profile"} {
			path := filepath.Join(home, name)
			if _, err := os.Stat(path); err == nil {
				profile = path
				break
			}
		}
		return append(files, profile), nil
	}
	return nil, fmt.Errorf("shell %q is not supported; use --shell bash or --shell zsh", shell)
}

// candidateRCFiles are every rc file bp may have edited, for detection.
func candidateRCFiles(env Env) []string {
	home := env.UserHome
	files := []string{filepath.Join(home, ".zshrc"), filepath.Join(home, ".bashrc"), filepath.Join(home, ".bash_profile"), filepath.Join(home, ".bash_login"), filepath.Join(home, ".profile")}
	if dir := env.getenv("ZDOTDIR"); dir != "" {
		files = append(files, filepath.Join(dir, ".zshrc"))
	}
	return files
}

func applySessions(env Env, journal *Journal) error {
	if env.Config.Legacy {
		// The server opens agents with bp open; it has no shell wrappers.
		return nil
	}
	if env.UserHome == "" {
		return errors.New("no home directory")
	}
	files, err := RCFiles(env)
	if err != nil {
		return err
	}
	if err := WriteShell(env, journal); err != nil {
		return err
	}
	for _, path := range files {
		if err := appendRCLine(path, journal); err != nil {
			return err
		}
	}
	return nil
}

// WriteShell writes (or refreshes) shell.sh and records it.
func WriteShell(env Env, journal *Journal) error {
	path := ShellPath(env.UserHome)
	content := LocalShell
	if env.Wrappers {
		content += CompatibilityWrappers
	} else if old, err := os.ReadFile(path); err == nil && strings.Contains(string(old), "_bp_install_compat") {
		// Keep wrappers a previous bp setup --wrappers installed.
		content += CompatibilityWrappers
	}
	journal.Record(Change{Kind: KindFile, Path: path, Marker: ShellMarker})
	if journal.DryRun() {
		return nil
	}
	if err := os.MkdirAll(filepath.Dir(path), 0700); err != nil {
		return err
	}
	return writeFileAtomic(path, []byte(content), 0600)
}

func appendRCLine(path string, journal *Journal) error {
	data, err := os.ReadFile(path)
	if err != nil && !os.IsNotExist(err) {
		return err
	}
	journal.Record(Change{Kind: KindLine, Path: path, Line: RCLine})
	if strings.Contains(string(data), RCLine) || journal.DryRun() {
		return nil
	}
	if err := os.MkdirAll(filepath.Dir(path), 0700); err != nil {
		return err
	}
	if len(data) > 0 {
		backup, err := os.CreateTemp(filepath.Dir(path), filepath.Base(path)+".before-bp-*")
		if err != nil {
			return err
		}
		_, writeErr := backup.Write(data)
		closeErr := backup.Close()
		if writeErr != nil {
			return writeErr
		}
		if closeErr != nil {
			return closeErr
		}
	}
	file, err := os.OpenFile(path, os.O_WRONLY|os.O_CREATE|os.O_APPEND, 0600)
	if err != nil {
		return err
	}
	_, writeErr := fmt.Fprintln(file, "\n"+RCLine)
	closeErr := file.Close()
	if writeErr != nil {
		return writeErr
	}
	return closeErr
}

// rcLinePresent reports the rc files that already carry bp's line.
func rcLinePresent(env Env) []string {
	var found []string
	seen := map[string]bool{}
	for _, path := range candidateRCFiles(env) {
		if seen[path] {
			continue
		}
		seen[path] = true
		data, err := os.ReadFile(path)
		if err == nil && strings.Contains(string(data), RCLine) {
			found = append(found, path)
		}
	}
	return found
}

func sessionsConflicts(env Env) []string {
	// The wrappers yield to existing functions and aliases, so nothing here
	// refuses; a user-owned shell.sh without bp's marker would be replaced.
	path := ShellPath(env.UserHome)
	if data, err := os.ReadFile(path); err == nil && !strings.Contains(string(data), ShellMarker) {
		return []string{path + " exists and was not written by bp"}
	}
	return nil
}
